# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/profiles/qemu-guest.nix")
  ];

  boot.initrd.availableKernelModules = ["nvme" "xhci_pci" "virtio_pci" "sd_mod" "virtio_blk"];
  boot.initrd.kernelModules = [];
  boot.kernelModules = ["kvm-intel"];
  boot.extraModulePackages = [];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/3918a8a1-d4d0-4ab3-91fd-8c9735b4a3c0";
    fsType = "ext4";
  };
  boot.initrd.luks.devices."luks-a318bf67-269b-4916-b7d9-7ef940dc513e".device = "/dev/disk/by-uuid/a318bf67-269b-4916-b7d9-7ef940dc513e";

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/376C-4A1F";
    fsType = "vfat";
  };

  swapDevices = [];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
